# Generated by Django 2.2.10 on 2020-02-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20200225_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometask',
            name='max_mark',
            field=models.IntegerField(default=100),
        ),
    ]
